# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('quote', models.TextField(max_length=1000)),
                ('posted_by', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.AddField(
            model_name='join',
            name='all_quotes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='everything', to='bb2.Quotes'),
        ),
        migrations.AddField(
            model_name='join',
            name='all_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='everyone', to='login.User'),
        ),
    ]
