# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
